#include "Fdm-stdinc.h"
#include "../../client/DCPlusPlus.h"
#include "Fdm-ResourceManager.h"
string FdmResourceManager::strings[] = {
"Active / Search String", 
"Autosearch Properties", 
"Close", 
"Enabled", 
"&Browse...", 
"&File", 
"&Help", 
"&View", 
"&Window", 
"Fdm Notepad", 
"Fdm Settings", 
"Auto-away on minimize (and back on restore)", 
"Autosearch", 
"Fdm Settings", 
"Fdm Notepad", 
"Only where op", 
"Search string", 
"Extra Appearance", 
"Text you write", 
"Your nick spoken", 
"If speaker is not an op", 
"If speaker is an op", 
"Note; most of these options require that you restart Fdm", 
"Text colouring", 
"Fdm Language file", 
"Size", 
"If size is", 
"Size is in", 
"Type of search", 
"False", 
"True", 
};
string FdmResourceManager::names[] = {
"ActiveSearchString", 
"AutoSearchProperties", 
"Close", 
"Enabled", 
"FdmBrowseAccel", 
"FdmMenuFile", 
"FdmMenuHelp", 
"FdmMenuView", 
"FdmMenuWindow", 
"FdmNotepad", 
"FdmSettings", 
"FdmSettingsAutoAway", 
"MenuAutoSearch", 
"MenuFdmSettings", 
"MenuNotepadFrame", 
"OnlyWhereOp", 
"SearchString", 
"SettingsAppearancePage", 
"SettingsAppearanceISpoke", 
"SettingsAppearanceMyNickSpoken", 
"SettingsAppearanceNotOpSpoke", 
"SettingsAppearanceOpSpoke", 
"SettingsAppearanceRequiresRestart", 
"SettingsAppearanceTextColouring", 
"SettingsFdmLanguageFile", 
"Size", 
"SizeModes", 
"SizeType", 
"SourceType", 
"StringFalse", 
"StringTrue", 
};
