// @Prolog: #include "stdinc.h"
// @Prolog: #include "../../client/DCPlusPlus.h"
// @Prolog: #include "Fdm-ResourceManager.h"
// @Strings: string FdmResourceManager::strings[]
// @Names: string FdmResourceManager::names[]

enum FdmStrings { // @DontAdd
	ACTIVE_SEARCH_STRING, // "Active / Search String"	
	AUTO_SEARCH_PROPERTIES, // "Autosearch Properties"
	AUTO_EXCLUDE_THESE, // "Exclude These Strings (Separate With A |)"
	AUTO_EXTENSION, // "One Of These Extensions (Separate With A |)"
	AUTO_MATCH_THESE, // "Match These Strings (Separate With A |)"
	COPY, // "Copy"
	CLOSE, // "Close"
	ENABLED, // "Enabled"
	FDM_BROWSE_ACCEL, // "&Browse..."
	FDM_MENU_FILE, // "&File"
	FDM_MENU_HELP, // "&Help"
	FDM_MENU_VIEW, // "&View"
	FDM_MENU_WINDOW, // "&Window"
	FDM_NOTEPAD, // "Fdm Notepad"
	FDM_SETTINGS, // "Fdm Settings"
	FDM_SETTINGS_AUTO_AWAY, // "Auto-away on minimize (and back on restore)"
	MAX_SIZE, // "Max size"
	MIN_SIZE, // "Min size"
	MENU_AUTO_SEARCH, // "Autosearch"
	MENU_FDM, // "&Fdm"
	MENU_FDM_ABOUT, // "About Fdm"
	MENU_FDM_SETTINGS, // "Fdm Settings"
	MENU_NOTEPAD_FRAME, // "Fdm Notepad"
	ONLY_WHERE_OP, // "Only where op"
	RESULTS, // "Results"
	SEARCH_STRING, // "Search string"
	SETTINGS_APPEARANCE_PAGE, // "Extra Appearance"
	SETTINGS_APPEARANCE_I_SPOKE, // "Text you write"
	SETTINGS_APPEARANCE_MY_NICK_SPOKEN, // "Your nick spoken"
	SETTINGS_APPEARANCE_NOT_OP_SPOKE, // "If speaker is not an op"
	SETTINGS_APPEARANCE_OP_SPOKE, // "If speaker is an op"
	SETTINGS_APPEARANCE_REQUIRES_RESTART, // "Note; most of these options require that you restart Fdm"
	SETTINGS_APPEARANCE_TEXT_COLOURING, // "Text colouring"
	SETTINGS_FDM_LANGUAGE_FILE, // "Fdm Language file"
	SIZE, // "Size"
	SIZE_MODES, // "If size is"
	SIZE_TYPE, // "Size is in"
	SOURCE_TYPE, // "Type of search"
	STRING_FALSE, // "False"
	STRING_TRUE, // "True"
	LAST // @DontAdd
};
