#include "stdinc.h"
#include "../../client/DCPlusPlus.h"
#include "Fdm-ResourceManager.h"
string FdmResourceManager::strings[] = {
"Active / Search String", 
"Autosearch Properties", 
"Exclude These Strings (Separate With A |)", 
"One Of These Extensions (Separate With A |)", 
"Match These Strings (Separate With A |)", 
"Copy", 
"Close", 
"Enabled", 
"&Browse...", 
"&File", 
"&Help", 
"&View", 
"&Window", 
"Fdm Notepad", 
"Fdm Settings", 
"Auto-away on minimize (and back on restore)", 
"Max size", 
"Min size", 
"Autosearch", 
"&Fdm", 
"About Fdm", 
"Fdm Settings", 
"Fdm Notepad", 
"Only where op", 
"Results", 
"Search string", 
"Extra Appearance", 
"Text you write", 
"Your nick spoken", 
"If speaker is not an op", 
"If speaker is an op", 
"Note; most of these options require that you restart Fdm", 
"Text colouring", 
"Fdm Language file", 
"Size", 
"If size is", 
"Size is in", 
"Type of search", 
"False", 
"True", 
};
string FdmResourceManager::names[] = {
"ActiveSearchString", 
"AutoSearchProperties", 
"AutoExcludeThese", 
"AutoExtension", 
"AutoMatchThese", 
"Copy", 
"Close", 
"Enabled", 
"FdmBrowseAccel", 
"FdmMenuFile", 
"FdmMenuHelp", 
"FdmMenuView", 
"FdmMenuWindow", 
"FdmNotepad", 
"FdmSettings", 
"FdmSettingsAutoAway", 
"MaxSize", 
"MinSize", 
"MenuAutoSearch", 
"MenuFdm", 
"MenuFdmAbout", 
"MenuFdmSettings", 
"MenuNotepadFrame", 
"OnlyWhereOp", 
"Results", 
"SearchString", 
"SettingsAppearancePage", 
"SettingsAppearanceISpoke", 
"SettingsAppearanceMyNickSpoken", 
"SettingsAppearanceNotOpSpoke", 
"SettingsAppearanceOpSpoke", 
"SettingsAppearanceRequiresRestart", 
"SettingsAppearanceTextColouring", 
"SettingsFdmLanguageFile", 
"Size", 
"SizeModes", 
"SizeType", 
"SourceType", 
"StringFalse", 
"StringTrue", 
};
