// @Prolog: #include "stdinc.h"
// @Prolog: #include "DCPlusPlus.h"
// @Prolog: #include "ResourceManager.h"
// @Prolog: namespace dcpp {
// @Strings: string ResourceManager::strings[]
// @Names: string ResourceManager::names[]
// @Epilog: } // namespace dcpp

enum Strings { // @DontAdd
	ACTIVE_SEARCH_STRING, // "Active / Search String"	
	AUTO_SEARCH_PROPERTIES, // "Autosearch Properties"
	AUTO_EXCLUDE_THESE, // "Exclude These Strings (Separate With A |)"
	AUTO_EXTENSION, // "One Of These Extensions (Separate With A |)"
	AUTO_MATCH_THESE, // "Match These Strings (Separate With A |)"
	AVERAGE, // "Average"
	FDM_BROWSE_ACCEL, // "&Browse..."
	FDM_SETTINGS_AUTO_AWAY, // "Auto-away on minimize (and back on restore)"
	MENU_AUTO_SEARCH, // "Autosearch"
	MENU_FDM, // "&Fdm"
	MENU_FDM_ABOUT, // "About Fdm"
	MENU_FDM_AUTOSEARCH, // "&Autosearch"
	MENU_FDM_AUTOSEARCH_FRAME, // "Autosearch"
	MENU_FDM_NOTEPAD, // "&Fdm Notepad"
	MENU_FDM_NOTEPAD_FRAME, // "Fdm Notepad"
	MENU_FDM_SETTINGS, // "Fdm Settings"
	ONLY_WHERE_OP, // "Only where op"
	OPTIONS, // "Options"
	RESULTS, // "Results"
	SETTINGS_APPEARANCE_PAGE, // "Fdm\\Extra Appearance"
	SETTINGS_APPEARANCE_I_SPOKE, // "Text you write"
	SETTINGS_APPEARANCE_MY_NICK_SPOKEN, // "Your nick spoken"
	SETTINGS_APPEARANCE_NOT_OP_SPOKE, // "If speaker is not an op"
	SETTINGS_APPEARANCE_OP_SPOKE, // "If speaker is an op"
	SETTINGS_APPEARANCE_REQUIRES_RESTART, // "Note; most of these options require that you restart Fdm"
	SETTINGS_APPEARANCE_SHOW_CC_IN_CHATS, // "Show Country Code of speaker in Main Chat and PMs"
	SETTINGS_APPEARANCE_SHOW_IPS_IN_CHATS, // "Show IPs of speaker in Main Chat and PMs"
	SETTINGS_APPEARANCE_TEXT_COLOURING, // "Text colouring"
	SETTINGS_BANDWIDTH, // "Fdm\\Bandwidth Limiting"
	SETTINGS_BANDWIDTH_AM, // "AM"	
	SETTINGS_BANDWIDTH_MIDNIGHT, // "Midnight"
	SETTINGS_BANDWIDTH_NOON, // "Noon"
	SETTINGS_BANDWIDTH_PM, // "PM"
	SETTINGS_BANDWIDTH_TEXT_MAXDOWNLOAD, // "Maximum Download Rate (KiB/s) (0 = infinite)"
	SETTINGS_BANDWIDTH_TEXT_MAXUPLOAD, // "Maximum Upload Rate (KiB/s) (0 = infinite)"
	SETTINGS_BANDWIDTH_TEXT_TIME_TRANSFER_RATE_LIMITING, // "Secondary Transfer Rate Limiting"
	SETTINGS_BANDWIDTH_TEXT_TO, // "to"
	SETTINGS_BANDWIDTH_TEXT_TRANSFER_RATE_LIMITING, // "Transfer Rate Limiting"
	SETTINGS_BANDWIDTH_TEXT_UPLOAD_SLOTS, // "Upload slots"
	SETTINGS_BANDWIDTH_THROTTLE_ENABLE, // "Enable Transfer Rate Limiting"
	SETTINGS_BANDWIDTH_THROTTLE_TIME_BASED_BW_LIMITING, // "Use second set of bandwidth limits from"
	SETTINGS_FDM_LANGUAGE_FILE, // "Fdm Language file"
	SIZE, // "Size"
	SIZE_MODES, // "If size is"
	SIZE_TYPE, // "Size is in"
	SOURCE_TYPE, // "Type of search"
	STRING_FALSE, // "False"
	STRING_TRUE, // "True"
	LAST // @DontAdd
};
